export const userType = {
  SET_FIRST_TIME: 'SET_FIRST_TIME',
  SET_AUDIT_CONTENT: 'SET_AUDIT_CONTENT',
  SET_ADMIN_ID: 'SET_ADMIN_ID',
  SET_ADMIN_AVATAR: 'SET_ADMIN_AVATAR',
  SET_ADMIN_NAME: 'SET_ADMIN_NAME',
  SET_ROLESID: 'SET_ROLESID',
  SET_COMPANY_ID: 'SET_COMPANY_ID',
  SET_ADMIN_TYPE: 'SET_ADMIN_TYPE',
  SET_SETTING: 'SET_SETTING'
}

export const appType = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  SIDEBAR_STATUS: 'SIDEBAR_STATUS',
  OPEN_SIDEBAR: 'OPEN_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  TOGGLE_DEVICE: 'TOGGLE_DEVICE',
  PAGE_LOADING: 'PAGE_LOADING',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_THEME: 'SET_THEME'
}

export const tagsViewType = {
  ADD_VISITED_VIEWS: 'ADD_VISITED_VIEWS',
  DEL_VISITED_VIEWS: 'DEL_VISITED_VIEWS',
  DEL_OTHERS_VIEWS: 'DEL_OTHERS_VIEWS',
  DEL_ALL_VIEWS: 'DEL_ALL_VIEWS'
}

export const errorLogType = {
  ADD_ERROR_LOG: 'ADD_ERROR_LOG'
}

export const systemType = {
  SET_MARK: 'SET_MARK'
}
